#
# Nightly build tasks
#

task:
  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191105
    cpu: 8
    memory: 24

  name: "x86-64-unknown-linux-gnu-nightly"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  test_script:
    -  bash .ci-scripts/x86-64-unknown-linux-gnu-nightly.bash ${CLOUDSMITH_API_KEY}

  only_if: $CIRRUS_API_CREATED == "true"

task:
  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191105
    cpu: 8
    memory: 24

  name: "x86-64-unknown-linux-musl-nightly"

  environment:
    CLOUDSMITH_API_KEY: ENCRYPTED[!2cb1e71c189cabf043ac3a9030b3c7708f9c4c983c86d07372ae58ad246a07c54e40810d038d31c3cf3ed8888350caca!]

  test_script:
    -  bash .ci-scripts/x86-64-unknown-linux-musl-nightly.bash ${CLOUDSMITH_API_KEY}

  only_if: $CIRRUS_API_CREATED == "true"

#
# Pull Request Tasks
#

task:
  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-gnu-builder:20191106
    cpu: 8
    memory: 24

  name: "lib/llvm: x86-64-unknown-linux-gnu"

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5sum lib/CMakeLists.txt` glibc"
    populate_script: make libs flags=-j8

  configure_script:
    - make configure
  build_script:
    - make build flags=-j8
  test_script:
    - make test-ci
  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release' && $CIRRUS_API_CREATED != "true"

task:
  container:
    image: ponylang/ponyc-ci-x86-64-unknown-linux-musl-builder:20191106
    cpu: 8
    memory: 24

  name: "lib/llvm: x86-64-unknown-linux-musl"

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5sum lib/CMakeLists.txt` musl"
    populate_script: make libs flags=-j8

  configure_script:
    - make configure
  build_script:
    - make build flags=-j8
  test_script:
    - make test-ci

  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release' && $CIRRUS_API_CREATED != "true"

task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
    cpu: 8
    memory: 24

  name: "lib/llvm: x86-64-unknown-freebsd12.0"

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y cmake gmake libunwind git

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5sum lib/CMakeLists.txt` freebsd12"
    populate_script: gmake libs flags=-j8

  configure_script:
    - gmake configure
  # build_script:
  #   - gmake build flags=-j8
  # test_script:
  #   - gmake test-ci

  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release' && $CIRRUS_API_CREATED != "true"

task:
  osx_instance:
    image: mojave-xcode-11.2.1

  name: "lib/llvm: macOS"

  install_script:
    - brew install coreutils

  libs_cache:
    folder: build/libs
    fingerprint_script: echo "`md5 lib/CMakeLists.txt` macos"
    populate_script: make libs flags=-j8

  configure_script:
    - make configure
  # build_script:
  #   - make build flags=-j8
  # test_script:
  #   - make test-ci

  only_if: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'release' && $CIRRUS_API_CREATED != "true"

task:
  windows_container:
    dockerfile: .ci-dockerfiles/windowsservercore/Dockerfile
    os_version: 2019

  name: "lib/llbm: Windows"

  timeout_in: 120m

  libs_cache:
    folder: build/libs
    fingerprint_script: powershell.exe -NoLogo -Command "(Get-FileHash -Path lib\CMakeLists.txt).Hash"
    populate_script: powershell.exe -NoLogo -File .\make.ps1 libs -Generator "Visual Studio 16 2019"

  config_script:
    - powershell.exe -NoLogo -File .\make.ps1 configure -Config Release -Generator "Visual Studio 16 2019" -InstallPath "build\install\release"
  # build_script:
  #   - powershell.exe -NoLogo -File .\make.ps1 build -Config Release -Generator "Visual Studio 16 2019" -InstallPath "build\install\release"
  # test_script:
  #   - powershell.exe -NoLogo -File .\make.ps1 test -Config Release -Generator "Visual Studio 16 2019" -InstallPath "build\install\release"

    # install_script: powershell.exe -NoLogo -File .\make.ps1 install -Config Release -InstallPath "build\install\release"
  # package_script: powershell.exe -NoLogo -File .\make.ps1 package -Config Release -InstallPath "build\install\release" -Version date
  # upload_script: powershell.exe -NoLogo -Command "$version = (Get-Date).ToString(""""yyyyMMdd""""); & cloudsmith push raw --version $version --api-key 1cc732891a064c6542e3632a6ee281b69dbdce18 --summary """"Pony compiler"""" --description """"https://github.com/ponylang/ponyc"""" main-pony/pony-nightlies build\ponyc-x86_64-pc-windows-msvc-$version.zip

  binary_artifacts:
    path: build/*.zip
